development:
  adapter: postgresql
  encoding: unicode
  database: control_dev
  #username: 
  #password:
  pool: 5
  timeout: 5000


test:
    adapter: postgresql
    encoding: unicode
    database: control_test
    #username: 
    #password:
    pool: 5
    timeout: 5000

production:
    adapter: postgresql
    encoding: unicode
    database: control_prod
    #username: 
    #password:
    pool: 5
    timeout: 5000